stages:
  - build
  - test

variables:
  DOTNET_SDK_IMAGE: "mcr.microsoft.com/dotnet/sdk:10.0"
  # Путь к кэшу NuGet для ускорения сборки
  NUGET_PACKAGES_LOOKUP: ".nuget/packages"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${NUGET_PACKAGES_LOOKUP}

# Этап сборки приложения
build_job:
  stage: build
  image: $DOTNET_SDK_IMAGE
  script:
    - dotnet restore --packages $NUGET_PACKAGES_LOOKUP
    - dotnet build --no-restore -c Release
  artifacts:
    paths:
      - "**/bin/Release/"
      - "**/obj/"
    expire_in: 1 hour

# Этап запуска тестов
test_job:
  stage: test
  image: $DOTNET_SDK_IMAGE
  dependencies:
    - build_job
  script:
    - dotnet test --no-build -c Release --logger:"junit;LogFilePath=test-results.xml"
  artifacts:
    when: always
    reports:
      junit: "**/test-results.xml"
